CPP       = g++
LINK      = g++

include Makefile.Objects

LIBS      = `wx-config --libs`

INCS      = 

BIN       = WarehouseDemoEnabler

CXXFLAGS  = $(INCS) \
			-O3 \
			`wx-config --cppflags`

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	rm -f $(OBJ) $(BIN)

open: all
	./$(BIN)

start: all
	./$(BIN)

$(BIN): $(OBJ)
	$(LINK) $(OBJ) -o $(BIN) $(LIBS)

.cpp.o:
	$(CPP) $(CXXFLAGS) -g -c $*.cpp -o $*.o
